#!/bin/sh
#
# baseagent        Starts baseagent.
#

NAME=baseagent
DAEMON=/usr/local/baseagent/$NAME
PID_FILE="/var/run/$NAME.pid"

start() {
        printf "Starting baseagent: "
        mkdir -p /var/run
        start-stop-daemon -S -q -m -b -p $PID_FILE -x $DAEMON
        echo "OK"
}

stop() {
        printf "Stopping baseagent: "
        if [ -f $PID_FILE ]; then
                start-stop-daemon -K -q -p $PID_FILE -s KILL -o
                sleep 1
                rm -f $PID_FILE
        fi
        echo "OK"
}

restart() {
        stop
        sleep 2
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
